### ISSUE TITLE
Unable to build - Babel errors

### ISSUE THREAD

**Issue by pronouncedJerry** [ipselon/structor-starter-prepack#2]
Error at step #3

1. Run command: npm install
2. Run command: npm run build-server
3. Run command: npm run build-client
4. Run command: node ./server.js 

ERROR in ./src/client/routes/HomePage.js
    Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/get-prototype-of' in /Users/daGod/Test Apps/structor/src/client/routes
     @ ./src/client/routes/HomePage.js 7:22-78

**Comment by ipselon** [comment]
@pronouncedJerry  it's my fault, there is no `babel-runtime` in package.json 
Please install `babel-runtime` manually so far, and I'll fix it soon.
Thanks.

**Comment by pronouncedJerry** [comment]
Ah, I'm learning. That worked. Thank you!
